#!/usr/bin/env bash
set -E -e -o pipefail

# Add repo specific metadata here.

BASE_IMAGE_CONFIG_KEY_PREFIX="BASE_IMAGE"

UPSTREAM_PACKAGE_NAME="LibreSpeed-go/Go"
UPSTREAM_LIBRESPEED_GO_VERSION_CONFIG_KEY="LIBRESPEED_GO_VERSION"
UPSTREAM_LIBRESPEED_GO_GIT_REPO="https://github.com/librespeed/speedtest-go"
UPSTREAM_GO_IMAGE_NAME_CONFIG_KEY="GO_IMAGE_NAME"
UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY="GO_IMAGE_TAG"
UPSTREAM_GO_IMAGE_PATTERN="^[0-9]+\.[0-9]+\.[0-9]+-go-.+$"

RELEASE_PACKAGE_NAME="LibreSpeed-go"
RELEASE_PACKAGE_VERSION_CONFIG_KEY="LIBRESPEED_GO_VERSION"
RELEASE_TAG_PACKAGE_NAME="librespeed-go"

TEST_TYPE="background"
TEST_CONTAINER_TYPE="librespeed-go"
TEST_CONTAINER_START_WAIT_SECONDS="10"

current_librespeed_go_version() {
    get_config_arg ${UPSTREAM_LIBRESPEED_GO_VERSION_CONFIG_KEY:?}
}

current_go_image_version() {
    get_config_arg ${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY:?}
}

current_upstream_version() {
    local librespeed_go_ver="$(current_librespeed_go_version)"
    local go_image_ver="$(current_go_image_version)"
    echo "${librespeed_go_ver:?}/${go_image_ver:?}"
}

latest_librespeed_go_version() {
    git -c 'versionsort.suffix=-' ls-remote \
        --exit-code \
        --refs \
        --sort='version:refname' \
        --tags \
        "${UPSTREAM_LIBRESPEED_GO_GIT_REPO:?}" | \
        cut --delimiter='/' --fields=3 | \
        sort --version-sort --reverse | \
        head -1
}

latest_go_image_version() {
    dockerhub_latest_tag \
        "$(get_config_arg ${UPSTREAM_GO_IMAGE_NAME_CONFIG_KEY:?})" \
        "${UPSTREAM_GO_IMAGE_PATTERN:?}"
}

latest_upstream_version() {
    local librespeed_go_ver="$(latest_librespeed_go_version)"
    local go_image_ver="$(latest_go_image_version)"
    echo "${librespeed_go_ver:?}/${go_image_ver:?}"
}

update_latest_upstream_version() {
    local cur_ver="${1:?}"
    local latest_ver="${2:?}"
    local cur_librespeed_go_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 1)"
    local cur_go_ver="$(echo "${cur_ver:?}" | cut -d '/' -f 2)"
    local latest_librespeed_go_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 1)"
    local latest_go_ver="$(echo "${latest_ver:?}" | cut -d '/' -f 2)"
    echo "Updating ${UPSTREAM_PACKAGE_NAME:?} ${UPSTREAM_LIBRESPEED_GO_VERSION_CONFIG_KEY:?}/${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY} '${cur_ver:?}' -> '${latest_ver:?}'"
    set_config_arg "${UPSTREAM_LIBRESPEED_GO_VERSION_CONFIG_KEY:?}" "${latest_librespeed_go_ver:?}"
    set_config_arg "${UPSTREAM_GO_IMAGE_TAG_CONFIG_KEY:?}" "${latest_go_ver:?}"
    git add ${ARGS_FILE:?}
}

package_current_release_version() {
    get_config_arg "${RELEASE_PACKAGE_VERSION_CONFIG_KEY:?}"
}

test_start_container() {
    local container_name="${1:?}"

    docker run \
        --user root \
        --name ${container_name:?} \
        --detach \
        --rm \
        ${IMAGE:?}
}

test_image_after_container_startup() {
    local container_name="${1:?}"
    local ip="$(container_ip "${container_name:?}")"
    test_http_endpoint "${container_name:?}" http ${ip:?} 8989
}
